### PR TITLE
use new symbole for validation

### PR DESCRIPTION
**Pull request by CedricCabessa**
3 configurable symbole are available:
  FEEDBACK_OK="LGTM"
  FEEDBACK_WEAK=":hand:"
  FEEDBACK_KO=":x:"

### CODE REVIEW

**Comment by mmaret-geny** [comment]
:+1:  :)

**Comment by mmaret-geny** [comment]
LGTM

**Comment by jcleneveu-geny** [comment]
Neeed. LGTM :dancer:

**Comment by fbarthelery** [comment]
LGTM

**Comment by AFouques** [comment]
LGTM :shipit:

**Pull request merged**
